/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package org.mozilla.reference.browser.agent.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateMapOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.CancellationException
import org.mozilla.reference.browser.agent.AgentAttachmentKind
import org.mozilla.reference.browser.agent.AgentAttachmentResult
import org.mozilla.reference.browser.agent.core.AgentApprovalDecision
import org.mozilla.reference.browser.agent.core.AgentApprovalRequest
import org.mozilla.reference.browser.agent.core.AgentConfig
import org.mozilla.reference.browser.agent.core.AgentMessage
import org.mozilla.reference.browser.agent.core.AgentPermissionTier
import org.mozilla.reference.browser.agent.core.ApiFormat
import org.mozilla.reference.browser.agent.core.Role

enum class PanelNav { Chat, Drawer, Settings, ModelSelector, Personalization, Memory, Advanced }

/** Reasoning effort tiers, mapped to a token budget (wired in a later round). */
enum class ReasonTier { Low, Middle, High }

/** Permission tiers shown on the model-selector slider. */
typealias PermTier = AgentPermissionTier
typealias ApprovalReq = AgentApprovalRequest

data class ToolCheckState(
    val status: String = "未测",
    val detail: String = "",
)

data class AgentAttachmentItem(
    val kind: AgentAttachmentKind,
    val uri: String,
    val displayName: String,
    val mimeType: String,
    val sizeBytes: Long,
)

/**
 * One saved conversation in the drawer. Holds both the display transcript ([messages]) and
 * the model transcript ([convo]) so tapping a recent chat fully restores it (view + continue),
 * not just its title. [titled] mirrors PanelState.titleGenerated for that chat.
 */
class SavedChat(
    val id: String,
    title: String,
    titled: Boolean = false,
    val messages: MutableList<ChatMsg> = mutableListOf(),
    val convo: MutableList<AgentMessage> = mutableListOf(),
) {
    var title by mutableStateOf(title)
    var titled by mutableStateOf(titled)
}

/**
 * UI state for the Agent panel. Conversation is in memory; provider settings, model
 * selection, permission tier, personalization, and memories are persisted by the host.
 */
class PanelState {
    val messages = mutableStateListOf<ChatMsg>()

    // Structured transcript fed to the model (system prompt is prepended per turn, not stored
    // here). Kept separate from [messages] (display-only) so tool calls / tool results survive
    // across turns without being reconstructed from rendered text.
    val convo = mutableListOf<AgentMessage>()
    var input by mutableStateOf("")
    var generating by mutableStateOf(false)
    var tempChat by mutableStateOf(false)
    var nav by mutableStateOf(PanelNav.Chat)
    var tier by mutableStateOf(ReasonTier.Middle)

    // Model list is driven by what the configured API key returns; empty → "暂无模型".
    val models = mutableStateListOf<String>()
    var selectedModel by mutableStateOf<String?>(null)
    var modelsLoading by mutableStateOf(false)

    // Recent conversations shown in the drawer. Each entry carries its full transcript so
    // tapping it reopens that conversation. currentChatId links the live messages/convo to one.
    val chats = mutableStateListOf<SavedChat>()
    var currentChatId by mutableStateOf<String?>(null)
    var currentChatTitle by mutableStateOf<String?>(null)

    // "我的 Agent": personalization style + durable memory.
    var persona by mutableStateOf("平衡")
    var memoryEnabled by mutableStateOf(true)
    var memorySummary by mutableStateOf("")
    var memoryUpdating by mutableStateOf(false)
    var memorySummaryError by mutableStateOf("")

    // Stored memories shown on the memory screen and injected into the system prompt.
    val memories = mutableStateListOf<String>()
    val attachments = mutableStateListOf<AgentAttachmentItem>()

    val toolChecks = mutableStateMapOf<String, ToolCheckState>()
    var toolsChecking by mutableStateOf(false)

    // Permission tier picked on the model-selector slider.
    var permTier by mutableStateOf(PermTier.S1)

    // "一键自动放行": when on, every tool call is approved without a confirmation sheet.
    // Default off; persisted by the host.
    var autoApproveAll by mutableStateOf(false)

    // Whether the current conversation already got an AI-generated title in [chats].
    // Reset on newChat so the next conversation gets its own title.
    var titleGenerated by mutableStateOf(false)

    // Secondary-confirmation (二次确认) state. pendingApproval drives the bottom sheet.
    // ApproveSession stores the request scope for this conversation only; it is not a
    // global "always allow this tool" grant.
    var pendingApproval by mutableStateOf<ApprovalReq?>(null)
    private var approvalWaiter: CompletableDeferred<AgentApprovalDecision>? = null
    private val approvalGrants = LinkedHashSet<String>()

    // Plan mode (mirrors the assistant's own enter/write/exit-plan flow). UI表征 only.
    var planMode by mutableStateOf(false)
    var planText by mutableStateOf("")

    // Provider/settings fields persisted by AgentSettingsStore.
    var apiKey by mutableStateOf("")
    var apiUrl by mutableStateOf("")
    var searchKey by mutableStateOf("")
    var searchUrl by mutableStateOf("")
    var anthropicFormat by mutableStateOf(false) // false = OpenAI, true = Anthropic

    // Backend hooks wired by the host (AgentPanelHost) to an AgentEngine/settings store.
    var onTurn: (() -> Unit)? = null
    var onStop: (() -> Unit)? = null
    var onLoadModels: (() -> Unit)? = null
    var onPersist: (() -> Unit)? = null
    var onToolSelfTest: ((String) -> Unit)? = null
    var onToolSelfTestAll: (() -> Unit)? = null
    var onGenerateMemorySummary: (() -> Unit)? = null
    var onPickAttachment: ((AgentAttachmentKind) -> Unit)? = null

    /** Builds a provider config from the current settings, or null if not usable yet. */
    fun buildConfig(requireModel: Boolean = true): AgentConfig? {
        val key = apiKey.trim()
        if (key.isEmpty()) return null
        val model = selectedModel?.trim().orEmpty()
        if (requireModel && model.isEmpty()) return null
        return AgentConfig(
            format = if (anthropicFormat) ApiFormat.Anthropic else ApiFormat.OpenAI,
            apiKey = key,
            baseUrl = apiUrl.trim(),
            model = model,
            maxTokens = when (tier) {
                ReasonTier.Low -> 700
                ReasonTier.Middle -> 1400
                ReasonTier.High -> 2400
            },
        )
    }

    fun send() {
        val text = input.trim()
        if (text.isEmpty()) return
        messages.add(ChatMsg(fromUser = true, text = text))
        convo.add(AgentMessage(Role.User, text))
        ensureCurrentChat(text)
        saveCurrentChat()
        input = ""
        generating = true
        onTurn?.invoke()
    }

    fun stop() {
        generating = false
        onStop?.invoke()
    }

    fun newChat() {
        onStop?.invoke()
        saveCurrentChat()
        messages.clear()
        convo.clear()
        approvalGrants.clear()
        generating = false
        input = ""
        planMode = false
        planText = ""
        titleGenerated = false
        currentChatId = null
        currentChatTitle = null
        attachments.clear()
        persist()
    }

    /**
     * Snapshot the live transcript into the current SavedChat so the drawer entry can be
     * reopened later. No-op for temp chats or before the first message creates a chat.
     */
    fun saveCurrentChat() {
        if (tempChat) return
        val id = currentChatId ?: return
        val chat = chats.firstOrNull { it.id == id } ?: return
        chat.messages.clear()
        chat.messages.addAll(messages)
        chat.convo.clear()
        chat.convo.addAll(convo)
        currentChatTitle?.let { chat.title = it }
        chat.titled = titleGenerated
        persist()
    }

    /** Reopen a saved conversation from the drawer: persist the current one, then load it. */
    fun loadChat(id: String) {
        if (id == currentChatId) {
            saveCurrentChat()
            nav = PanelNav.Chat
            return
        }
        onStop?.invoke()
        saveCurrentChat()
        val chat = chats.firstOrNull { it.id == id } ?: return
        messages.clear()
        messages.addAll(chat.messages)
        convo.clear()
        convo.addAll(chat.convo)
        approvalGrants.clear()
        currentChatId = chat.id
        currentChatTitle = chat.title
        titleGenerated = chat.titled
        generating = false
        input = ""
        planMode = false
        planText = ""
        attachments.clear()
        nav = PanelNav.Chat
        persist()
    }

    /**
     * Plan-card "批准并开始": dismiss the plan card and feed the approval back into the
     * engine so the model continues automatically (instead of the turn ending and the user
     * having to re-send). Injects an approval note into the transcript and starts a turn.
     */
    fun approvePlan() {
        planMode = false
        saveCurrentChat()
        if (generating) return
        convo.add(AgentMessage(Role.User, "我已批准上面的计划，请按计划继续执行，不需要再次确认计划本身。"))
        saveCurrentChat()
        generating = true
        onTurn?.invoke()
    }

    fun persist() {
        onPersist?.invoke()
    }

    fun updateMemorySummary(value: String) {
        memorySummary = value.take(4000)
        memorySummaryError = ""
        persist()
    }

    fun addMemory(value: String = "") {
        memories.add(value.take(1000))
        persist()
    }

    fun updateMemory(index: Int, value: String) {
        if (index !in memories.indices) return
        memories[index] = value.take(1000)
        persist()
    }

    fun removeMemory(index: Int) {
        if (index !in memories.indices) return
        memories.removeAt(index)
        persist()
    }

    fun mergeMemoryUpdate(summary: String, items: List<String>) {
        val cleanedSummary = summary.trim().take(4000)
        if (cleanedSummary.isNotEmpty()) memorySummary = cleanedSummary
        if (cleanedSummary.isNotEmpty() || items.isNotEmpty()) memorySummaryError = ""
        val seen = memories.map { it.trim().lowercase() }.toMutableSet()
        items.map { it.trim().replace(Regex("\\s+"), " ") }
            .filter { it.length in 3..1000 }
            .forEach { item ->
                val key = item.lowercase()
                if (seen.add(key)) memories.add(item)
            }
        while (memories.size > 40) memories.removeAt(0)
        persist()
    }

    fun generateMemorySummary() {
        memorySummaryError = ""
        onGenerateMemorySummary?.invoke()
    }

    fun pickAttachment(kind: AgentAttachmentKind) {
        if (kind == AgentAttachmentKind.Plugin) {
            messages.add(ChatMsg(fromUser = false, text = "插件入口在网页 DevTools 的「拓展」面板里，当前悬浮窗已保留这个入口。"))
            saveCurrentChat()
            return
        }
        onPickAttachment?.invoke(kind)
    }

    fun addAttachment(result: AgentAttachmentResult) {
        val item = AgentAttachmentItem(
            kind = result.kind,
            uri = result.uri,
            displayName = result.displayName.ifBlank { defaultAttachmentName(result.kind) },
            mimeType = result.mimeType,
            sizeBytes = result.sizeBytes,
        )
        attachments.add(item)
        val label = when (item.kind) {
            AgentAttachmentKind.Camera -> "相机"
            AgentAttachmentKind.Image -> "图片"
            AgentAttachmentKind.File -> "文件"
            AgentAttachmentKind.Plugin -> "插件"
        }
        val size = if (item.sizeBytes >= 0) "，${item.sizeBytes} bytes" else ""
        val text = "已添加$label：${item.displayName}"
        messages.add(ChatMsg(fromUser = true, text = text))
        convo.add(
            AgentMessage(
                Role.User,
                "（附件）$label：${item.displayName}；uri=${item.uri}；mime=${item.mimeType.ifBlank { "未知" }}$size",
            ),
        )
        ensureCurrentChat(text)
        saveCurrentChat()
    }

    /**
     * Switches the permission tier. The system prompt is authoritative and rebuilt each turn,
     * but if a conversation is already underway we also drop an explicit note into the
     * transcript so the model sees the change without needing a fresh conversation.
     */
    fun selectPermTier(tier: PermTier) {
        if (permTier == tier) {
            persist()
            return
        }
        permTier = tier
        if (convo.isNotEmpty()) {
            convo.add(AgentMessage(Role.User, "（系统提示）当前权限层已切换为 ${tier.name}，后续一律以 ${tier.name} 为准。"))
            saveCurrentChat()
        }
        persist()
    }

    suspend fun requestApproval(req: ApprovalReq): AgentApprovalDecision {
        if (autoApproveAll) return AgentApprovalDecision.Approve
        approvalWaiter?.complete(AgentApprovalDecision.Deny)
        val waiter = CompletableDeferred<AgentApprovalDecision>()
        approvalWaiter = waiter
        pendingApproval = req
        return try {
            waiter.await()
        } catch (_: CancellationException) {
            AgentApprovalDecision.Deny
        } finally {
            if (approvalWaiter === waiter) {
                approvalWaiter = null
                pendingApproval = null
            }
        }
    }

    fun hasApprovalGrant(scopeKey: String): Boolean = autoApproveAll || approvalGrants.contains(scopeKey)

    fun resolveApproval(decision: AgentApprovalDecision) {
        val req = pendingApproval
        if (decision == AgentApprovalDecision.ApproveSession && req != null) {
            approvalGrants.add(req.scopeKey)
        }
        val waiter = approvalWaiter
        approvalWaiter = null
        pendingApproval = null
        waiter?.complete(decision)
    }

    private fun ensureCurrentChat(text: String) {
        if (tempChat || currentChatId != null) return
        val title = localTitle(text)
        if (title.isBlank()) return
        val chat = SavedChat(id = java.util.UUID.randomUUID().toString(), title = title)
        chat.messages.addAll(messages)
        chat.convo.addAll(convo)
        chats.add(0, chat)
        currentChatId = chat.id
        currentChatTitle = title
        trimChats()
        persist()
    }

    fun replaceCurrentTitle(title: String) {
        if (tempChat) return
        val cleaned = title.trim().replace(Regex("\\s+"), " ").take(20)
        if (cleaned.isBlank()) return
        currentChatTitle = cleaned
        val id = currentChatId
        val chat = if (id != null) chats.firstOrNull { it.id == id } else null
        if (chat != null) {
            chat.title = cleaned
            chat.titled = titleGenerated
        }
        trimChats()
        persist()
    }

    private fun trimChats() {
        while (chats.size > 20) chats.removeAt(chats.size - 1)
    }

    private fun localTitle(text: String): String =
        text.trim()
            .replace(Regex("\\s+"), " ")
            .trimStart('（', '(', '[', '【')
            .take(16)
            .ifBlank { "新对话" }

    private fun defaultAttachmentName(kind: AgentAttachmentKind): String = when (kind) {
        AgentAttachmentKind.Camera -> "camera.jpg"
        AgentAttachmentKind.Image -> "image"
        AgentAttachmentKind.File -> "file"
        AgentAttachmentKind.Plugin -> "plugin"
    }
}

@Composable
fun rememberPanelState(): PanelState = remember { PanelState() }
